name: Create single commit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INITIAL_COMMIT: 58dc14c148f481a6ad48119825f1f0e78339e17b
    steps:
      - uses: actions/checkout@v1
      - name: Configure GIT
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Commit files
        run: python3 contrib/filter-commits.py
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: refs/heads/branch2
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}